# Generated by Django 2.1.7 on 2019-03-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190310_2021'),
        ('analytics', '0002_remove_view_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=150)),
                ('count', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('activation_time', models.DateTimeField(blank=True)),
                ('deactivation_time', models.DateTimeField(blank=True)),
                ('voted_users', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
