# Generated by Django 2.1.7 on 2019-03-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_featuresurvey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresurvey',
            name='voted_users',
        ),
    ]
