# Generated by Django 2.1.7 on 2019-03-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190310_2021'),
        ('analytics', '0004_remove_featuresurvey_voted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresurvey',
            name='voted_users',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
