# Generated by Django 2.1.8 on 2019-05-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_featuresurvey_voted_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresurvey',
            name='voted_users',
        ),
        migrations.DeleteModel(
            name='FeatureSurvey',
        ),
    ]
